version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps: 
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@65.1.125.185 "cd /var/www/html/online-shopping && git pull origin master"
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the main branch
