version: 2.1

jobs:
  hold-for-approval:
    machine:
      enabled: true
    steps:
      - run:
          name: Wait for Approval
          command: |
            echo "Hold for Approval"
  deploy:
    machine:
      enabled: true
    steps: 
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.108.135.33 "cd /var/www/html/online-shopping && git pull origin slave" 
workflows:
  build-and-deploy:
    jobs:
      - hold-for-approval:
         type: approval
      - deploy:
          requires:
            - hold-for-approval
          filters:
            branches:
              only: slave # only deploy on the slave branch