version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'    
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.235.134.107 "cd /var/www/html/online-shopping && git pull origin slave"      
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: slave # only deploy on the main branch
      - Hold-for-Approval:
          type: approval
          requires:
            - deploy
