version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps: 
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.235.134.107 "cd /var/www/html/online-shopping && git pull origin slave"
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'      
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
<<<<<<< HEAD
              only: master # only deploy on the main branch
      - Hold-for-Approval:
          type: approval
          requires:
            - deploy
      - Now-Complete:
          requires:
            - Hold-for-Approval     
=======
              only: slave # only deploy on the main branch
>>>>>>> 98366ff7606499347a2eeda678ad9b91d5224c6f
